version: '3.7'

services:
  smartorder-postgres:
    image: bitnami/postgresql
    ports:
      - '5432:5432'
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=smartorder
    volumes:
      - postgres_data:/bitnami/postgresql

volumes:
  postgres_data:
